import './scss/style.scss';
import './components/header/header.js';
import './components/apartmentCard/apartmentCard.js';
// import './components/searchForm/searchForm.js';
import './components/priceForm/priceForm.js';
import './components/rangeSlider/rangeSlider.js';

import Logo from './assets/Logo.svg';
import arrowFooter from './assets/arrow_footer.svg';
import facebook from './assets/facebook.svg';
import twitter from './assets/twitter.svg';
import instagram from './assets/instagram.svg';
import headerMenuArrow from './assets/header-menu-arrow.svg';
import arrowForward from './assets/arrow_forward.svg';
import apartmentOne from './assets/apartment-one.png';
import apartmentTwo from './assets/apartment-two.png';
import apartmentThree from './assets/apartment-three.png';
import star from './assets/star.svg';
import starOutline from './assets/star-outline.svg';
import sliderNext from './assets/slider_next.svg';
import sliderPrev from './assets/slider_prev.svg';